name: Deploy to ISPmanager server
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=yes rasulovtokhir@83.69.139.161 << 'EOF'
            set -e
            cd /www/mopify.uz
            git fetch --all
            git reset --hard origin/main
            npm ci
            npm run build
            pm2 reload mopify || pm2 start npm --name mopify -- start
            pm2 save
          EOF
